---
blank_issues_enabled: false
contact_links:
  -
    about: Propose new features
    name: ğŸ’¡ Feature requests
    url: https://github.com/node-oauth/node-oauth2-server/discussions/categories/ideas
  -
    about: Ask a question or for help
    name: â“ Question
    url: https://github.com/node-oauth/node-oauth2-server/discussions/categories/q-a
  -
    about: Chat on our discord
    name: ğŸ—¯ Chat
    url: https://discord.gg/4HTUAcTvqV
  -
    about: Read the documentation
    name: ğŸ“œ Documentation
    url: https://node-oauthoauth2-server.readthedocs.io/en/latest/
